version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    steps:
      - checkout
      - restore_cache_cmd
      - run: ./mvnw test
      - save_cache_cmd
      - store_test_results:
          path: ~/test-results/
  build:
    steps:
      - checkout
      - restore_cache_cmd
      - run: ./mvnw -Dmaven.test.skip=true package
      - save_cache_cmd

executors:
 docker-executor:
   docker:
     - image: bellsoft/liberica-openjdk-alpine

jobs:
  test-with-docker:
    executor: docker-executor
    steps:
      - test

  build-with-docker:
    executor: docker-executor
    steps:
      - build


workflows:
  build-then-test-with-docker:
    jobs:
      - build-with-docker
      - test-with-docker:
          requires:
            - build-with-docker
